definitions:
  common_adapters.ErrorDetail:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  common_adapters.ErrorMessage:
    properties:
      message:
        type: string
    type: object
  common_adapters.ErrorMessageWithDetails:
    properties:
      details:
        items:
          $ref: '#/definitions/common_adapters.ErrorDetail'
        type: array
      message:
        type: string
    type: object
  confirm_email.ConfirmEmailInput:
    properties:
      token:
        type: string
    type: object
  login.LoginInputDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  login.LoginOutputDTO:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  signup.SignupInputDTO:
    properties:
      birth:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/confirm-email:
    post:
      consumes:
      - application/json
      description: Confirm the user's email.
      parameters:
      - description: Corpo da solicitação
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/confirm_email.ConfirmEmailInput'
      produces:
      - application/json
      responses:
        "204":
          description: Email successfully confirmed
        "400":
          description: 'Bad Request: Token expired or invalid'
          schema:
            $ref: '#/definitions/common_adapters.ErrorMessageWithDetails'
        "404":
          description: 'Not Found: User not found'
          schema:
            $ref: '#/definitions/common_adapters.ErrorMessage'
        "409":
          description: 'Conflict: Email already confirmed'
          schema:
            $ref: '#/definitions/common_adapters.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common_adapters.ErrorMessage'
      summary: Confirm email
      tags:
      - Auth
  /api/v1/auth/signup:
    post:
      consumes:
      - application/json
      description: Register a user.
      parameters:
      - description: Corpo da solicitação
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/signup.SignupInputDTO'
      produces:
      - application/json
      responses:
        "204":
          description: User successfully registered
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common_adapters.ErrorMessageWithDetails'
        "409":
          description: Email already exists
          schema:
            $ref: '#/definitions/common_adapters.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common_adapters.ErrorMessage'
      summary: Register a user
      tags:
      - Auth
  /login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/login.LoginInputDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.LoginOutputDTO'
      summary: Login
      tags:
      - Auth
swagger: "2.0"
